language: node_js
node_js:
- '6'
script:
- npm run test:ci
notifications:
  email: false
deploy:
  provider: npm
  email: miau@motane.lu
  api_key:
    secure: bgXrNq0S0zGOPHWOK7EBnEvem5Zw3/3S4lOk6NiMrlMzU4Bb7e1YQAibmaYAxKmJ3gempbvOgk6/7fEcuzeNAYM4sXJslsQWgxIbA/0xZTZeAmmHIyCT5kurRMWxQ9P0bue9N1S2PbZOkTF568T9VcXv0LRYHDDC+1vmP914nKILYxc0zMKz1F8K9Jk/LM3lXThNZm90pK69DV10Fc+yry1jcE44SqRVmmEzbEs4m3UltsxriOFpu0arcAYHBl2lWZ2YNqcy0ElJ6Bxzo6ymaszMEga2jeWXkUx0ToRyxjJvd33Lx/uAojoWDLp7OGWs9Ua1xS/kwdI7FTk8ZmQO7QfKMXnt6cWJnd4AZQ0lL9DURraoHyXVHFBDdkEuebFaK7mD+ankqQP1kw2Sy/eNJHCxZU7BXZAmhnMSy6MokIYReJpyz9DLW+cqOWi8P/1pdgbCERE7w267HuulIlZTjFjMUDtypqYi7dyXghL2MZSDLpWU3atxFyef4WZlZMee6RMAx1Z4G4TBHSR5BWkGiddHbw3Ea9SmkEBCldSaXuXx9+4gkAuwznHjIYcnHmtkgthgyKX1+JM+QB2z2SSm4FybJWmH9LwnPYtWaQeZIW9lr8jzG9tRSLUUmZrqZ4is4sA3z7tvihYkecnLtLT/Ahj+QePr2AgNF3OMpGrraGk=
  on:
    tags: true
    repo: motanelu/clocky
